version: '3'

services:
  openvpn:
    image: croc/openvpn:2.5.1-debian11
    environment:
#     - SERVER_ADDRESS=<your public ip>
      - SERVER_PORT=51194
      - PROTO=udp
      - KEY_COUNTRY=HU
      - KEY_PROVINCE=HU
      - KEY_CITY=Budapest
      - KEY_ORG=My Tech Company
      - KEY_EMAIL=vpn@my-tech-company.com
      - KEY_OU=IT NETWORK
      - VPN_NETWORK=10.88.77.0/24
      - VPN_IS_DEFAULTGW=no
#      - IPV6_ADDRESS=auto
#      - IPV6_VPN_IS_DEFAULTGW=yes
#      - RADIUS_SERVER=127.0.0.1
#      - RADIUS_SECRET=secret
    volumes:
      - './config:/etc/openvpn'
    network_mode: host
    #ports:
    #  - '51194:51194/udp'
    #  - '51194:51194/tcp'
    privileged: true
    restart: unless-stopped
